export interface UseCaseConfig {
  id: string;
  name: string;
  icon: string;
  description: string;
  category: 'security' | 'traffic' | 'safety' | 'operations';
  color: string;
  bgColor: string;
}

export const useCases: UseCaseConfig[] = [
  {
    id: 'crowd-estimation',
    name: 'Crowd Estimation',
    icon: '👥',
    description: 'Monitor crowd density with real-time statistics and directional flow analysis',
    category: 'operations',
    color: '#3B82F6',
    bgColor: '#DBEAFE',
  },
  {
    id: 'heatmap',
    name: 'Heat Map',
    icon: '🔥',
    description: 'Visual representation of person and vehicle movement patterns',
    category: 'operations',
    color: '#EF4444',
    bgColor: '#FEE2E2',
  },
  {
    id: 'entry-exit',
    name: 'Entry/Exit Count',
    icon: '📊',
    description: 'Track people movement in and out of designated areas',
    category: 'operations',
    color: '#10B981',
    bgColor: '#D1FAE5',
  },
  {
    id: 'person-attributes',
    name: 'Person Attributes',
    icon: '🔍',
    description: 'Analyze and search by clothing, bags, colors, and other attributes',
    category: 'security',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
  },
  {
    id: 'abandoned-objects',
    name: 'Abandoned Objects',
    icon: '⚠️',
    description: 'Detect unattended bags, objects, and potential threats',
    category: 'security',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
  },
  {
    id: 'intruder-alert',
    name: 'Intruder Alert',
    icon: '🚨',
    description: 'Monitor restricted zones and detect unauthorized intrusions',
    category: 'security',
    color: '#DC2626',
    bgColor: '#FEE2E2',
  },
  {
    id: 'violence-detection',
    name: 'Violence Detection',
    icon: '⚡',
    description: 'Automatically detect and alert on violent incidents',
    category: 'safety',
    color: '#DC2626',
    bgColor: '#FEE2E2',
  },
  {
    id: 'gesture-recognition',
    name: 'Gesture Recognition',
    icon: '✋',
    description: 'Monitor and analyze human gestures and body language',
    category: 'security',
    color: '#06B6D4',
    bgColor: '#CFFAFE',
  },
  {
    id: 'fire-smoke',
    name: 'Fire & Smoke Detection',
    icon: '🔥',
    description: 'Early detection of fire and smoke hazards',
    category: 'safety',
    color: '#EA580C',
    bgColor: '#FFEDD5',
  },
  {
    id: 'helmet-violation',
    name: 'Helmet Violation',
    icon: '🪖',
    description: 'Detect riders without proper safety helmets',
    category: 'safety',
    color: '#EC4899',
    bgColor: '#FCE7F3',
  },
  {
    id: 'triple-riding',
    name: 'Triple Riding',
    icon: '🏍️',
    description: 'Monitor and alert on vehicles with excessive passengers',
    category: 'traffic',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
  },
  {
    id: 'seatbelt',
    name: 'Seat Belt Violation',
    icon: '🚗',
    description: 'Verify proper seat belt usage in vehicles',
    category: 'safety',
    color: '#EC4899',
    bgColor: '#FCE7F3',
  },
  {
    id: 'wrong-way',
    name: 'Wrong Way Detection',
    icon: '🚫',
    description: 'Detect vehicles traveling in prohibited directions',
    category: 'traffic',
    color: '#DC2626',
    bgColor: '#FEE2E2',
  },
  {
    id: 'parking-violation',
    name: 'Parking Violation',
    icon: '🅿️',
    description: 'Monitor illegal parking and dwell violations',
    category: 'traffic',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
  },
  {
    id: 'animal-detection',
    name: 'Animal Detection',
    icon: '🐄',
    description: 'Detect stray animals on routes and restricted areas',
    category: 'safety',
    color: '#92400E',
    bgColor: '#FEF3C7',
  },
  {
    id: 'debris',
    name: 'Debris Detection',
    icon: '🗑️',
    description: 'Alert on debris and obstacles on roadways',
    category: 'safety',
    color: '#64748B',
    bgColor: '#F1F5F9',
  },
  {
    id: 'queue-management',
    name: 'Queue Management',
    icon: '📋',
    description: 'Monitor queue lengths and optimize flow',
    category: 'operations',
    color: '#0891B2',
    bgColor: '#CFFAFE',
  },
  {
    id: 'stolen-vehicle',
    name: 'Stolen Vehicle Alert',
    icon: '🚗',
    description: 'Detect and track reported stolen vehicles',
    category: 'security',
    color: '#DC2626',
    bgColor: '#FEE2E2',
  },
];

export const categoryColors = {
  security: { color: '#DC2626', bgColor: '#FEE2E2' },
  traffic: { color: '#F59E0B', bgColor: '#FEF3C7' },
  safety: { color: '#8B5CF6', bgColor: '#EDE9FE' },
  operations: { color: '#10B981', bgColor: '#D1FAE5' },
};
